---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLE_PATH: ../roles/
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint: |
    set -e
    flake8
